// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW2oa44LE5gMxCz-r3Geqf5_MD99chpc8',
    appId: '1:194872592168:web:2e334014bdc7066e58721d',
    messagingSenderId: '194872592168',
    projectId: 'ecom-4d4eb',
    authDomain: 'ecom-4d4eb.firebaseapp.com',
    storageBucket: 'ecom-4d4eb.firebasestorage.app',
    measurementId: 'G-QCBZDM3SN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYv_3MLw3wWBxC9pXKgTePNXG9cqNmAMA',
    appId: '1:194872592168:android:0607f0368249095b58721d',
    messagingSenderId: '194872592168',
    projectId: 'ecom-4d4eb',
    storageBucket: 'ecom-4d4eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVbMCIdUF5K7x43HtLDyvW5Uwa2qIhyI0',
    appId: '1:194872592168:ios:bc25e7ff5a67010558721d',
    messagingSenderId: '194872592168',
    projectId: 'ecom-4d4eb',
    storageBucket: 'ecom-4d4eb.firebasestorage.app',
    iosBundleId: 'com.example.ecom',
  );
}
